from typing import Any

def __getattr__(name: str) -> Any: ...

# Generated from the runtime mujoco module so basedpyright can see pybind exports.
FatalError: type[Any]
GLContext: type[Any]
HEADERS_DIR: Any
MJTNUM_BYTES: Any
MJTNUM_DTYPE: type[Any]
MjByteVec: type[Any]
MjCharVec: type[Any]
MjContact: type[Any]
MjData: type[Any]
MjDoubleVec: type[Any]
MjFloatVec: type[Any]
MjIntVec: type[Any]
MjLROpt: type[Any]
MjLogConfig: type[Any]
MjLogMessage: type[Any]
MjModel: type[Any]
MjOption: type[Any]
MjPreContact: type[Any]
MjSolverStat: type[Any]
MjSpec: type[Any]
MjStatistic: type[Any]
MjStringVec: type[Any]
MjStruct: Any
MjTimerStat: type[Any]
MjVfs: type[Any]
MjVisual: type[Any]
MjVisualHeadlight: type[Any]
MjVisualRgba: type[Any]
MjWarningStat: type[Any]
MjrContext: type[Any]
MjrRect: type[Any]
MjrVertexAttribute: type[Any]
MjsActuator: type[Any]
MjsAuthored: type[Any]
MjsBody: type[Any]
MjsCamera: type[Any]
MjsCompiler: type[Any]
MjsDefault: type[Any]
MjsElement: type[Any]
MjsEquality: type[Any]
MjsExclude: type[Any]
MjsFlex: type[Any]
MjsFrame: type[Any]
MjsGeom: type[Any]
MjsHField: type[Any]
MjsJoint: type[Any]
MjsKey: type[Any]
MjsLight: type[Any]
MjsMaterial: type[Any]
MjsMesh: type[Any]
MjsNumeric: type[Any]
MjsOrientation: type[Any]
MjsPair: type[Any]
MjsPlugin: type[Any]
MjsSensor: type[Any]
MjsSite: type[Any]
MjsSkin: type[Any]
MjsTendon: type[Any]
MjsTendonPath: type[Any]
MjsText: type[Any]
MjsTexture: type[Any]
MjsTuple: type[Any]
MjsWrap: type[Any]
MjvCamera: type[Any]
MjvFigure: type[Any]
MjvGLCamera: type[Any]
MjvGeom: type[Any]
MjvLight: type[Any]
MjvOption: type[Any]
MjvPerturb: type[Any]
MjvScene: type[Any]
PLUGINS_DIR: Any
PLUGIN_HANDLES: Any
Renderer: type[Any]
UnexpectedError: type[Any]
cgl: Any
def from_zip(*args: Any, **kwargs: Any) -> Any: ...
def get_mjcb_act_bias(*args: Any, **kwargs: Any) -> Any: ...
def get_mjcb_act_dyn(*args: Any, **kwargs: Any) -> Any: ...
def get_mjcb_act_gain(*args: Any, **kwargs: Any) -> Any: ...
def get_mjcb_contactfilter(*args: Any, **kwargs: Any) -> Any: ...
def get_mjcb_control(*args: Any, **kwargs: Any) -> Any: ...
def get_mjcb_passive(*args: Any, **kwargs: Any) -> Any: ...
def get_mjcb_sensor(*args: Any, **kwargs: Any) -> Any: ...
def get_mjcb_time(*args: Any, **kwargs: Any) -> Any: ...
def get_mju_user_free(*args: Any, **kwargs: Any) -> Any: ...
def get_mju_user_malloc(*args: Any, **kwargs: Any) -> Any: ...
def get_mju_user_warning(*args: Any, **kwargs: Any) -> Any: ...
is_rosetta: Any
mjDISABLESTRING: Any
mjENABLESTRING: Any
mjFRAMESTRING: Any
mjLABELSTRING: Any
mjMAXCONPAIR: Any
mjMAXFLEXNODES: Any
mjMAXIMP: Any
mjMAXLIGHT: Any
mjMAXLINE: Any
mjMAXLINEPNT: Any
mjMAXOVERLAY: Any
mjMAXPLANEGRID: Any
mjMAXTREEDEPTH: Any
mjMAXVAL: Any
mjMINAWAKE: Any
mjMINIMP: Any
mjMINMU: Any
mjMINVAL: Any
mjNBIAS: Any
mjNDYN: Any
mjNEQDATA: Any
mjNFLUID: Any
mjNGAIN: Any
mjNGROUP: Any
mjNIMP: Any
mjNISLAND: Any
mjNPOLY: Any
mjNREF: Any
mjNSENS: Any
mjNSOLVER: Any
mjPI: Any
mjRNDSTRING: Any
mjTIMERSTRING: Any
mjVERSION_HEADER: Any
mjVISSTRING: Any
def mj_Euler(*args: Any, **kwargs: Any) -> Any: ...
def mj_RungeKutta(*args: Any, **kwargs: Any) -> Any: ...
def mj_addContact(*args: Any, **kwargs: Any) -> Any: ...
def mj_addM(*args: Any, **kwargs: Any) -> Any: ...
def mj_angmomMat(*args: Any, **kwargs: Any) -> Any: ...
def mj_applyFT(*args: Any, **kwargs: Any) -> Any: ...
def mj_camlight(*args: Any, **kwargs: Any) -> Any: ...
def mj_checkAcc(*args: Any, **kwargs: Any) -> Any: ...
def mj_checkPos(*args: Any, **kwargs: Any) -> Any: ...
def mj_checkVel(*args: Any, **kwargs: Any) -> Any: ...
def mj_clearCache(*args: Any, **kwargs: Any) -> Any: ...
def mj_collision(*args: Any, **kwargs: Any) -> Any: ...
def mj_comPos(*args: Any, **kwargs: Any) -> Any: ...
def mj_comVel(*args: Any, **kwargs: Any) -> Any: ...
def mj_compareFwdInv(*args: Any, **kwargs: Any) -> Any: ...
def mj_constraintUpdate(*args: Any, **kwargs: Any) -> Any: ...
def mj_contactForce(*args: Any, **kwargs: Any) -> Any: ...
def mj_copyData(*args: Any, **kwargs: Any) -> Any: ...
def mj_copyState(*args: Any, **kwargs: Any) -> Any: ...
def mj_crb(*args: Any, **kwargs: Any) -> Any: ...
def mj_defaultLROpt(*args: Any, **kwargs: Any) -> Any: ...
def mj_defaultOption(*args: Any, **kwargs: Any) -> Any: ...
def mj_defaultSolRefImp(*args: Any, **kwargs: Any) -> Any: ...
def mj_defaultVisual(*args: Any, **kwargs: Any) -> Any: ...
def mj_differentiatePos(*args: Any, **kwargs: Any) -> Any: ...
def mj_energyPos(*args: Any, **kwargs: Any) -> Any: ...
def mj_energyVel(*args: Any, **kwargs: Any) -> Any: ...
def mj_extractState(*args: Any, **kwargs: Any) -> Any: ...
def mj_factorM(*args: Any, **kwargs: Any) -> Any: ...
def mj_flex(*args: Any, **kwargs: Any) -> Any: ...
def mj_forward(*args: Any, **kwargs: Any) -> Any: ...
def mj_forwardSkip(*args: Any, **kwargs: Any) -> Any: ...
def mj_fullM(*args: Any, **kwargs: Any) -> Any: ...
def mj_fwdAcceleration(*args: Any, **kwargs: Any) -> Any: ...
def mj_fwdActuation(*args: Any, **kwargs: Any) -> Any: ...
def mj_fwdConstraint(*args: Any, **kwargs: Any) -> Any: ...
def mj_fwdKinematics(*args: Any, **kwargs: Any) -> Any: ...
def mj_fwdPosition(*args: Any, **kwargs: Any) -> Any: ...
def mj_fwdVelocity(*args: Any, **kwargs: Any) -> Any: ...
def mj_geomDistance(*args: Any, **kwargs: Any) -> Any: ...
def mj_getCache(*args: Any, **kwargs: Any) -> Any: ...
def mj_getCacheCapacity(*args: Any, **kwargs: Any) -> Any: ...
def mj_getCacheSize(*args: Any, **kwargs: Any) -> Any: ...
def mj_getState(*args: Any, **kwargs: Any) -> Any: ...
def mj_getTotalmass(*args: Any, **kwargs: Any) -> Any: ...
def mj_id2name(*args: Any, **kwargs: Any) -> Any: ...
def mj_implicit(*args: Any, **kwargs: Any) -> Any: ...
def mj_initCtrlHistory(*args: Any, **kwargs: Any) -> Any: ...
def mj_initSensorHistory(*args: Any, **kwargs: Any) -> Any: ...
def mj_integratePos(*args: Any, **kwargs: Any) -> Any: ...
def mj_invConstraint(*args: Any, **kwargs: Any) -> Any: ...
def mj_invPosition(*args: Any, **kwargs: Any) -> Any: ...
def mj_invVelocity(*args: Any, **kwargs: Any) -> Any: ...
def mj_inverse(*args: Any, **kwargs: Any) -> Any: ...
def mj_inverseSkip(*args: Any, **kwargs: Any) -> Any: ...
def mj_isDual(*args: Any, **kwargs: Any) -> Any: ...
def mj_isPyramidal(*args: Any, **kwargs: Any) -> Any: ...
def mj_isSparse(*args: Any, **kwargs: Any) -> Any: ...
def mj_island(*args: Any, **kwargs: Any) -> Any: ...
def mj_jac(*args: Any, **kwargs: Any) -> Any: ...
def mj_jacBody(*args: Any, **kwargs: Any) -> Any: ...
def mj_jacBodyCom(*args: Any, **kwargs: Any) -> Any: ...
def mj_jacDot(*args: Any, **kwargs: Any) -> Any: ...
def mj_jacGeom(*args: Any, **kwargs: Any) -> Any: ...
def mj_jacPointAxis(*args: Any, **kwargs: Any) -> Any: ...
def mj_jacSite(*args: Any, **kwargs: Any) -> Any: ...
def mj_jacSubtreeCom(*args: Any, **kwargs: Any) -> Any: ...
def mj_kinematics(*args: Any, **kwargs: Any) -> Any: ...
def mj_loadAllPluginLibraries(*args: Any, **kwargs: Any) -> Any: ...
def mj_loadPluginLibrary(*args: Any, **kwargs: Any) -> Any: ...
def mj_local2Global(*args: Any, **kwargs: Any) -> Any: ...
def mj_makeConstraint(*args: Any, **kwargs: Any) -> Any: ...
def mj_makeM(*args: Any, **kwargs: Any) -> Any: ...
def mj_maxContact(*args: Any, **kwargs: Any) -> Any: ...
def mj_mulJacTVec(*args: Any, **kwargs: Any) -> Any: ...
def mj_mulJacVec(*args: Any, **kwargs: Any) -> Any: ...
def mj_mulM(*args: Any, **kwargs: Any) -> Any: ...
def mj_mulM2(*args: Any, **kwargs: Any) -> Any: ...
def mj_multiRay(*args: Any, **kwargs: Any) -> Any: ...
def mj_name2id(*args: Any, **kwargs: Any) -> Any: ...
def mj_normalizeQuat(*args: Any, **kwargs: Any) -> Any: ...
def mj_objectAcceleration(*args: Any, **kwargs: Any) -> Any: ...
def mj_objectVelocity(*args: Any, **kwargs: Any) -> Any: ...
def mj_passive(*args: Any, **kwargs: Any) -> Any: ...
def mj_printData(*args: Any, **kwargs: Any) -> Any: ...
def mj_printFormattedData(*args: Any, **kwargs: Any) -> Any: ...
def mj_printFormattedModel(*args: Any, **kwargs: Any) -> Any: ...
def mj_printFormattedScene(*args: Any, **kwargs: Any) -> Any: ...
def mj_printModel(*args: Any, **kwargs: Any) -> Any: ...
def mj_printScene(*args: Any, **kwargs: Any) -> Any: ...
def mj_printSchema(*args: Any, **kwargs: Any) -> Any: ...
def mj_projectConstraint(*args: Any, **kwargs: Any) -> Any: ...
def mj_ray(*args: Any, **kwargs: Any) -> Any: ...
def mj_rayFlex(*args: Any, **kwargs: Any) -> Any: ...
def mj_rayHfield(*args: Any, **kwargs: Any) -> Any: ...
def mj_rayMesh(*args: Any, **kwargs: Any) -> Any: ...
def mj_readCtrl(*args: Any, **kwargs: Any) -> Any: ...
def mj_readSensor(*args: Any, **kwargs: Any) -> Any: ...
def mj_referenceConstraint(*args: Any, **kwargs: Any) -> Any: ...
def mj_resetCallbacks(*args: Any, **kwargs: Any) -> Any: ...
def mj_resetData(*args: Any, **kwargs: Any) -> Any: ...
def mj_resetDataDebug(*args: Any, **kwargs: Any) -> Any: ...
def mj_resetDataKeyframe(*args: Any, **kwargs: Any) -> Any: ...
def mj_rne(*args: Any, **kwargs: Any) -> Any: ...
def mj_rnePostConstraint(*args: Any, **kwargs: Any) -> Any: ...
def mj_saveLastXML(*args: Any, **kwargs: Any) -> Any: ...
def mj_saveModel(*args: Any, **kwargs: Any) -> Any: ...
def mj_sensorAcc(*args: Any, **kwargs: Any) -> Any: ...
def mj_sensorPos(*args: Any, **kwargs: Any) -> Any: ...
def mj_sensorVel(*args: Any, **kwargs: Any) -> Any: ...
def mj_setCacheCapacity(*args: Any, **kwargs: Any) -> Any: ...
def mj_setConst(*args: Any, **kwargs: Any) -> Any: ...
def mj_setKeyframe(*args: Any, **kwargs: Any) -> Any: ...
def mj_setLengthRange(*args: Any, **kwargs: Any) -> Any: ...
def mj_setState(*args: Any, **kwargs: Any) -> Any: ...
def mj_setTotalmass(*args: Any, **kwargs: Any) -> Any: ...
def mj_sizeModel(*args: Any, **kwargs: Any) -> Any: ...
def mj_solveM(*args: Any, **kwargs: Any) -> Any: ...
def mj_solveM2(*args: Any, **kwargs: Any) -> Any: ...
def mj_stateSize(*args: Any, **kwargs: Any) -> Any: ...
def mj_step(*args: Any, **kwargs: Any) -> Any: ...
def mj_step1(*args: Any, **kwargs: Any) -> Any: ...
def mj_step2(*args: Any, **kwargs: Any) -> Any: ...
def mj_subtreeVel(*args: Any, **kwargs: Any) -> Any: ...
def mj_tendon(*args: Any, **kwargs: Any) -> Any: ...
def mj_transmission(*args: Any, **kwargs: Any) -> Any: ...
def mj_version(*args: Any, **kwargs: Any) -> Any: ...
def mj_versionString(*args: Any, **kwargs: Any) -> Any: ...
def mjd_inverseFD(*args: Any, **kwargs: Any) -> Any: ...
def mjd_quatIntegrate(*args: Any, **kwargs: Any) -> Any: ...
def mjd_subQuat(*args: Any, **kwargs: Any) -> Any: ...
def mjd_transitionFD(*args: Any, **kwargs: Any) -> Any: ...
mjrIndexType: type[Any]
mjrMeshPrimitiveType: type[Any]
mjrPixelFormat: type[Any]
mjrVertexAttributeType: type[Any]
mjrVertexAttributeUsage: type[Any]
def mjr_addAux(*args: Any, **kwargs: Any) -> Any: ...
def mjr_blitAux(*args: Any, **kwargs: Any) -> Any: ...
def mjr_blitBuffer(*args: Any, **kwargs: Any) -> Any: ...
def mjr_changeFont(*args: Any, **kwargs: Any) -> Any: ...
def mjr_drawPixels(*args: Any, **kwargs: Any) -> Any: ...
def mjr_figure(*args: Any, **kwargs: Any) -> Any: ...
def mjr_findRect(*args: Any, **kwargs: Any) -> Any: ...
def mjr_finish(*args: Any, **kwargs: Any) -> Any: ...
def mjr_getError(*args: Any, **kwargs: Any) -> Any: ...
def mjr_label(*args: Any, **kwargs: Any) -> Any: ...
def mjr_maxViewport(*args: Any, **kwargs: Any) -> Any: ...
def mjr_overlay(*args: Any, **kwargs: Any) -> Any: ...
def mjr_readPixels(*args: Any, **kwargs: Any) -> Any: ...
def mjr_rectangle(*args: Any, **kwargs: Any) -> Any: ...
def mjr_render(*args: Any, **kwargs: Any) -> Any: ...
def mjr_resizeOffscreen(*args: Any, **kwargs: Any) -> Any: ...
def mjr_restoreBuffer(*args: Any, **kwargs: Any) -> Any: ...
def mjr_setAux(*args: Any, **kwargs: Any) -> Any: ...
def mjr_setBuffer(*args: Any, **kwargs: Any) -> Any: ...
def mjr_text(*args: Any, **kwargs: Any) -> Any: ...
def mjr_uploadHField(*args: Any, **kwargs: Any) -> Any: ...
def mjr_uploadMesh(*args: Any, **kwargs: Any) -> Any: ...
def mjr_uploadTexture(*args: Any, **kwargs: Any) -> Any: ...
mjtAlignFree: type[Any]
mjtBias: type[Any]
mjtBuiltin: type[Any]
mjtButton: type[Any]
mjtCTimer: type[Any]
mjtCamLight: type[Any]
mjtCamOutBit: type[Any]
mjtCamera: type[Any]
mjtCatBit: type[Any]
mjtColorSpace: type[Any]
mjtConDataField: type[Any]
mjtCone: type[Any]
mjtConflict: type[Any]
mjtConstraint: type[Any]
mjtConstraintState: type[Any]
mjtDataType: type[Any]
mjtDepthMap: type[Any]
mjtDisableBit: type[Any]
mjtDyn: type[Any]
mjtEnableBit: type[Any]
mjtEq: type[Any]
mjtEvent: type[Any]
mjtFlexSelf: type[Any]
mjtFont: type[Any]
mjtFontScale: type[Any]
mjtFrame: type[Any]
mjtFramebuffer: type[Any]
mjtGain: type[Any]
mjtGeom: type[Any]
mjtGeomInertia: type[Any]
mjtGridPos: type[Any]
mjtInertiaFromGeom: type[Any]
mjtIntegrator: type[Any]
mjtItem: type[Any]
mjtJacobian: type[Any]
mjtJoint: type[Any]
mjtLRMode: type[Any]
mjtLabel: type[Any]
mjtLightType: type[Any]
mjtLimited: type[Any]
mjtLogLevel: type[Any]
mjtLogTopic: type[Any]
mjtMark: type[Any]
mjtMeshBuiltin: type[Any]
mjtMeshInertia: type[Any]
mjtMouse: type[Any]
mjtObj: type[Any]
mjtOrientation: type[Any]
mjtPertBit: type[Any]
mjtPluginCapabilityBit: type[Any]
mjtProjection: type[Any]
mjtRayDataField: type[Any]
mjtRndFlag: type[Any]
mjtSDFType: type[Any]
mjtSameFrame: type[Any]
mjtSection: type[Any]
mjtSensor: type[Any]
mjtSleepPolicy: type[Any]
mjtSleepState: type[Any]
mjtSolver: type[Any]
mjtStage: type[Any]
mjtState: type[Any]
mjtStereo: type[Any]
mjtTexture: type[Any]
mjtTextureRole: type[Any]
mjtTimer: type[Any]
mjtTrn: type[Any]
mjtVisFlag: type[Any]
mjtWarning: type[Any]
mjtWrap: type[Any]
def mju_Halton(*args: Any, **kwargs: Any) -> Any: ...
def mju_L1(*args: Any, **kwargs: Any) -> Any: ...
def mju_add(*args: Any, **kwargs: Any) -> Any: ...
def mju_add3(*args: Any, **kwargs: Any) -> Any: ...
def mju_addScl(*args: Any, **kwargs: Any) -> Any: ...
def mju_addScl3(*args: Any, **kwargs: Any) -> Any: ...
def mju_addTo(*args: Any, **kwargs: Any) -> Any: ...
def mju_addTo3(*args: Any, **kwargs: Any) -> Any: ...
def mju_addToScl(*args: Any, **kwargs: Any) -> Any: ...
def mju_addToScl3(*args: Any, **kwargs: Any) -> Any: ...
def mju_axisAngle2Quat(*args: Any, **kwargs: Any) -> Any: ...
def mju_band2Dense(*args: Any, **kwargs: Any) -> Any: ...
def mju_bandDiag(*args: Any, **kwargs: Any) -> Any: ...
def mju_bandMulMatVec(*args: Any, **kwargs: Any) -> Any: ...
def mju_boxQP(*args: Any, **kwargs: Any) -> Any: ...
def mju_cholFactor(*args: Any, **kwargs: Any) -> Any: ...
def mju_cholFactorBand(*args: Any, **kwargs: Any) -> Any: ...
def mju_cholSolve(*args: Any, **kwargs: Any) -> Any: ...
def mju_cholSolveBand(*args: Any, **kwargs: Any) -> Any: ...
def mju_cholUpdate(*args: Any, **kwargs: Any) -> Any: ...
def mju_clip(*args: Any, **kwargs: Any) -> Any: ...
def mju_copy(*args: Any, **kwargs: Any) -> Any: ...
def mju_copy3(*args: Any, **kwargs: Any) -> Any: ...
def mju_copy4(*args: Any, **kwargs: Any) -> Any: ...
def mju_cross(*args: Any, **kwargs: Any) -> Any: ...
def mju_d2n(*args: Any, **kwargs: Any) -> Any: ...
def mju_decodePyramid(*args: Any, **kwargs: Any) -> Any: ...
def mju_dense2Band(*args: Any, **kwargs: Any) -> Any: ...
def mju_dense2sparse(*args: Any, **kwargs: Any) -> Any: ...
def mju_derivQuat(*args: Any, **kwargs: Any) -> Any: ...
def mju_dist3(*args: Any, **kwargs: Any) -> Any: ...
def mju_dot(*args: Any, **kwargs: Any) -> Any: ...
def mju_dot3(*args: Any, **kwargs: Any) -> Any: ...
def mju_eig3(*args: Any, **kwargs: Any) -> Any: ...
def mju_encodePyramid(*args: Any, **kwargs: Any) -> Any: ...
def mju_euler2Quat(*args: Any, **kwargs: Any) -> Any: ...
def mju_eye(*args: Any, **kwargs: Any) -> Any: ...
def mju_f2n(*args: Any, **kwargs: Any) -> Any: ...
def mju_fill(*args: Any, **kwargs: Any) -> Any: ...
def mju_getXMLDependencies(*args: Any, **kwargs: Any) -> Any: ...
def mju_insertionSort(*args: Any, **kwargs: Any) -> Any: ...
def mju_insertionSortInt(*args: Any, **kwargs: Any) -> Any: ...
def mju_isBad(*args: Any, **kwargs: Any) -> Any: ...
def mju_isZero(*args: Any, **kwargs: Any) -> Any: ...
def mju_mat2Quat(*args: Any, **kwargs: Any) -> Any: ...
def mju_mat2Rot(*args: Any, **kwargs: Any) -> Any: ...
def mju_max(*args: Any, **kwargs: Any) -> Any: ...
def mju_min(*args: Any, **kwargs: Any) -> Any: ...
def mju_mulMatMat(*args: Any, **kwargs: Any) -> Any: ...
def mju_mulMatMatT(*args: Any, **kwargs: Any) -> Any: ...
def mju_mulMatTMat(*args: Any, **kwargs: Any) -> Any: ...
def mju_mulMatTVec(*args: Any, **kwargs: Any) -> Any: ...
def mju_mulMatTVec3(*args: Any, **kwargs: Any) -> Any: ...
def mju_mulMatVec(*args: Any, **kwargs: Any) -> Any: ...
def mju_mulMatVec3(*args: Any, **kwargs: Any) -> Any: ...
def mju_mulPose(*args: Any, **kwargs: Any) -> Any: ...
def mju_mulQuat(*args: Any, **kwargs: Any) -> Any: ...
def mju_mulQuatAxis(*args: Any, **kwargs: Any) -> Any: ...
def mju_mulVecMatVec(*args: Any, **kwargs: Any) -> Any: ...
def mju_muscleBias(*args: Any, **kwargs: Any) -> Any: ...
def mju_muscleDynamics(*args: Any, **kwargs: Any) -> Any: ...
def mju_muscleGain(*args: Any, **kwargs: Any) -> Any: ...
def mju_n2d(*args: Any, **kwargs: Any) -> Any: ...
def mju_n2f(*args: Any, **kwargs: Any) -> Any: ...
def mju_negPose(*args: Any, **kwargs: Any) -> Any: ...
def mju_negQuat(*args: Any, **kwargs: Any) -> Any: ...
def mju_norm(*args: Any, **kwargs: Any) -> Any: ...
def mju_norm3(*args: Any, **kwargs: Any) -> Any: ...
def mju_normalize(*args: Any, **kwargs: Any) -> Any: ...
def mju_normalize3(*args: Any, **kwargs: Any) -> Any: ...
def mju_normalize4(*args: Any, **kwargs: Any) -> Any: ...
def mju_printMat(*args: Any, **kwargs: Any) -> Any: ...
def mju_printMatSparse(*args: Any, **kwargs: Any) -> Any: ...
def mju_quat2Mat(*args: Any, **kwargs: Any) -> Any: ...
def mju_quat2Vel(*args: Any, **kwargs: Any) -> Any: ...
def mju_quatIntegrate(*args: Any, **kwargs: Any) -> Any: ...
def mju_quatZ2Vec(*args: Any, **kwargs: Any) -> Any: ...
def mju_rayGeom(*args: Any, **kwargs: Any) -> Any: ...
def mju_raySkin(*args: Any, **kwargs: Any) -> Any: ...
def mju_rotVecQuat(*args: Any, **kwargs: Any) -> Any: ...
def mju_round(*args: Any, **kwargs: Any) -> Any: ...
def mju_scl(*args: Any, **kwargs: Any) -> Any: ...
def mju_scl3(*args: Any, **kwargs: Any) -> Any: ...
def mju_sigmoid(*args: Any, **kwargs: Any) -> Any: ...
def mju_sign(*args: Any, **kwargs: Any) -> Any: ...
def mju_sparse2dense(*args: Any, **kwargs: Any) -> Any: ...
def mju_springDamper(*args: Any, **kwargs: Any) -> Any: ...
def mju_sqrMatTD(*args: Any, **kwargs: Any) -> Any: ...
def mju_standardNormal(*args: Any, **kwargs: Any) -> Any: ...
def mju_str2Type(*args: Any, **kwargs: Any) -> Any: ...
def mju_sub(*args: Any, **kwargs: Any) -> Any: ...
def mju_sub3(*args: Any, **kwargs: Any) -> Any: ...
def mju_subFrom(*args: Any, **kwargs: Any) -> Any: ...
def mju_subFrom3(*args: Any, **kwargs: Any) -> Any: ...
def mju_subQuat(*args: Any, **kwargs: Any) -> Any: ...
def mju_sum(*args: Any, **kwargs: Any) -> Any: ...
def mju_sym2dense(*args: Any, **kwargs: Any) -> Any: ...
def mju_symmetrize(*args: Any, **kwargs: Any) -> Any: ...
def mju_threadpool(*args: Any, **kwargs: Any) -> Any: ...
def mju_transformSpatial(*args: Any, **kwargs: Any) -> Any: ...
def mju_transpose(*args: Any, **kwargs: Any) -> Any: ...
def mju_trnVecPose(*args: Any, **kwargs: Any) -> Any: ...
def mju_type2Str(*args: Any, **kwargs: Any) -> Any: ...
def mju_unit4(*args: Any, **kwargs: Any) -> Any: ...
def mju_warningText(*args: Any, **kwargs: Any) -> Any: ...
def mju_writeLog(*args: Any, **kwargs: Any) -> Any: ...
def mju_writeNumBytes(*args: Any, **kwargs: Any) -> Any: ...
def mju_zero(*args: Any, **kwargs: Any) -> Any: ...
def mju_zero3(*args: Any, **kwargs: Any) -> Any: ...
def mju_zero4(*args: Any, **kwargs: Any) -> Any: ...
def mjv_addGeoms(*args: Any, **kwargs: Any) -> Any: ...
def mjv_alignToCamera(*args: Any, **kwargs: Any) -> Any: ...
def mjv_applyPerturbForce(*args: Any, **kwargs: Any) -> Any: ...
def mjv_applyPerturbPose(*args: Any, **kwargs: Any) -> Any: ...
def mjv_averageCamera(*args: Any, **kwargs: Any) -> Any: ...
def mjv_cameraFrame(*args: Any, **kwargs: Any) -> Any: ...
def mjv_cameraFrustum(*args: Any, **kwargs: Any) -> Any: ...
def mjv_cameraInModel(*args: Any, **kwargs: Any) -> Any: ...
def mjv_cameraInRoom(*args: Any, **kwargs: Any) -> Any: ...
def mjv_connector(*args: Any, **kwargs: Any) -> Any: ...
def mjv_defaultCamera(*args: Any, **kwargs: Any) -> Any: ...
def mjv_defaultFigure(*args: Any, **kwargs: Any) -> Any: ...
def mjv_defaultFreeCamera(*args: Any, **kwargs: Any) -> Any: ...
def mjv_defaultOption(*args: Any, **kwargs: Any) -> Any: ...
def mjv_defaultPerturb(*args: Any, **kwargs: Any) -> Any: ...
def mjv_frustumHeight(*args: Any, **kwargs: Any) -> Any: ...
def mjv_initGeom(*args: Any, **kwargs: Any) -> Any: ...
def mjv_initPerturb(*args: Any, **kwargs: Any) -> Any: ...
def mjv_makeLights(*args: Any, **kwargs: Any) -> Any: ...
def mjv_model2room(*args: Any, **kwargs: Any) -> Any: ...
def mjv_moveCamera(*args: Any, **kwargs: Any) -> Any: ...
def mjv_moveModel(*args: Any, **kwargs: Any) -> Any: ...
def mjv_movePerturb(*args: Any, **kwargs: Any) -> Any: ...
def mjv_room2model(*args: Any, **kwargs: Any) -> Any: ...
def mjv_select(*args: Any, **kwargs: Any) -> Any: ...
def mjv_updateCamera(*args: Any, **kwargs: Any) -> Any: ...
def mjv_updateScene(*args: Any, **kwargs: Any) -> Any: ...
def mjv_updateSkin(*args: Any, **kwargs: Any) -> Any: ...
proc_translated: Any
rendering: Any
def set_mjcb_act_bias(*args: Any, **kwargs: Any) -> Any: ...
def set_mjcb_act_dyn(*args: Any, **kwargs: Any) -> Any: ...
def set_mjcb_act_gain(*args: Any, **kwargs: Any) -> Any: ...
def set_mjcb_contactfilter(*args: Any, **kwargs: Any) -> Any: ...
def set_mjcb_control(*args: Any, **kwargs: Any) -> Any: ...
def set_mjcb_passive(*args: Any, **kwargs: Any) -> Any: ...
def set_mjcb_sensor(*args: Any, **kwargs: Any) -> Any: ...
def set_mjcb_time(*args: Any, **kwargs: Any) -> Any: ...
def set_mju_user_free(*args: Any, **kwargs: Any) -> Any: ...
def set_mju_user_malloc(*args: Any, **kwargs: Any) -> Any: ...
def set_mju_user_warning(*args: Any, **kwargs: Any) -> Any: ...
def to_zip(*args: Any, **kwargs: Any) -> Any: ...
